export {
  AuthService,
  type AuthServiceOptions,
  type RegisteredUser,
  type LoginResult,
  type LoginOutcome,
  type SessionIdentity,
  type MembershipSummary,
  type MfaSetup,
  type MfaStatus,
} from './service.js';
export { hashPassword, verifyPassword } from './passwords.js';
export { generateToken, hashToken, type GeneratedToken } from './tokens.js';
export {
  generateTotpSecret,
  hotpCode,
  totpCode,
  totpStep,
  verifyTotp,
  otpauthUri,
  base32Encode,
  base32Decode,
  encryptSecret,
  decryptSecret,
  encryptMfaSecret,
  decryptMfaSecret,
  decryptMfaSecretWithKeyring,
  toMfaKeyring,
  parseMfaKey,
  DEV_MFA_SECRET_KEY_HEX,
  TOTP_DIGITS,
  TOTP_STEP_SECONDS,
  type MfaEncKeyring,
  type VerifyTotpOptions,
} from './totp.js';
export {
  inspectMfaSecretKeys,
  reencryptMfaSecrets,
  type MfaSecretKeyStatus,
  type ReencryptMfaSecretsResult,
} from './rotate-mfa.js';
export {
  RegisterSchema,
  LoginSchema,
  VerifyEmailSchema,
  PasswordSchema,
  MfaVerifySchema,
  MfaCodeOnlySchema,
  StepUpPasswordSchema,
  type RegisterInput,
  type LoginInput,
  type VerifyEmailInput,
  type MfaVerifyInput,
  type MfaCodeOnlyInput,
  type StepUpPasswordInput,
} from './schemas.js';
export {
  AuthError,
  EmailTakenError,
  InvalidCredentialsError,
  EmailNotVerifiedError,
  AccountLockedError,
  InvalidSessionError,
  InvalidVerificationTokenError,
  InvalidMfaCodeError,
  InvalidMfaChallengeError,
  MfaAlreadyEnabledError,
  MfaNotEnabledError,
  StepUpRequiredError,
  RateLimitedError,
} from './errors.js';
